### ISSUE TITLE
FreeType error

### ISSUE THREAD

**Issue by SemnoSao** [M-Reimer/wine-lol#34] opened 2019-10-15 22:53 UTC
I keep getting this error even with freetype2 and lib32-freetype2 being installed, not really sure what to do

`configure: error: FreeType 32-bit development files not found. Fonts will not be built.
Use the --without-freetype option if you really want this.
==> ERROR: A failure occurred in build().
    Aborting...
:: Unable to build wine-lol - makepkg exited with code: 4
`
thanks for any help

**Comment by M-Reimer** [comment] 2019-10-16 04:06
Get sure wine-lol-glibc version matches your system glibc version. If your system glibc is 2.30, then update wine-lol-glibc first

**Comment by M-Reimer** [comment] 2019-10-17 05:57
Duplicate of #28
Fix: Update wine-lol-glibc first

**Closed by M-Reimer** 2019-10-17 05:57 UTC

**Comment by nichiporenko** [comment] 2023-04-22 00:27
How to get this `wine-lol-glibc`?
```
yay -S wine-lol-glibc 
 -> No AUR package found for wine-lol-glibc
 there is nothing to do

```

**Comment by M-Reimer** [comment] 2023-04-22 03:11
> How to get this `wine-lol-glibc`?

You are commenting on a (very) old issue. "wine-lol-glibc" was needed as a dependency of "wine-lol" but it is no longer needed.
