### ISSUE TITLE
glibc 2.32 breaks window positioning and resolution

### ISSUE THREAD

**Issue by lolzballs** [M-Reimer/wine-lol#58] opened 2020-08-28 13:18 UTC
After upgrading to glibc 2.32, whenever the client requests to position its window, it moves itself to the top of the screen. As well, only the lowest client resolution is available (1024x576).

I'm running i3 on Arch Linux, latest kernel, DXVK enabled. My system runs an R5 2600 w/ an RX 580.

I'm happy to debug this issue if it's not reproducible, but I'm not sure how a glibc update would break something related to X and nothing else.

**Comment by M-Reimer** [comment] 2020-08-28 13:45
I won't be able to really debug this.

Can you try to only update glibc and keep an older wine-lol build (maybe my binary)? There is a chance that some other library on arch contains a change that would require a wine update.

**Comment by lolzballs** [comment] 2020-08-28 14:01
When I downgrade to the 2.31 version of `wine-lol-glibc`, with no other changes to my system the windowing works correctly. I installed `gnome-shell` and it works there in 2.32 so I suppose it is isolated to i3 or tiling window managers in general. If I enable the virtual wine desktop it works there, so it seems like something in i3 is reporting weirdly.

Are you a wine developer? I can try to look into this if you have some pointers on where to start.

**Comment by M-Reimer** [comment] 2020-08-28 14:30
Keep the new glibc, use my binary wine-lol.

And no, I'm no wine developer.

**Comment by M-Reimer** [comment] 2020-08-28 16:43
Sorry for the short comments but I was on my phone.

I'm no wine developer and my knowledge about wine internals is very limited. But I doubt that the reason for the problem is really glibc. If it would be, then there should be more (even native) applications with this issue.
My guess is that, if you rebuilt wine after building glibc, wine got rebuilt with new headers of updated libraries which somehow causes this problem. Maybe our wine 5.6 is too old to still be compiled against the up-to-date libraries shippped with Arch.

As it is no option to keep an older glibc (just won't work on Arch) the only solution could be to update wine to a more recent version. But to rule this out it would be important to find out that the rebuilt wine is really the issue here.

That's why I want you to only update glibc and use a older wine package which still was successfully built against the old wine-lol-glibc version.

**Comment by lolzballs** [comment] 2020-08-28 17:31
I agree, it doesn't make sense that the problem is with glibc since the game itself runs fine apart from the client issues I mentioned.

The wine-lol version I was originally running was compiled from AUR before I updated wine-lol-glibc. I tried rebuilding it now (with 2.32) and it unfortunately still had the same issue.

I also tried the wine-lol from your repo and it still has the same issue. It seems like wine-lol-glibc in that repo is still 2.31, so I can't try it with yours.

I will try upgrading wine to 5.11 w/ glibc 2.31 now. I know you've been working on this but have you determined the patchset yet?

**Comment by M-Reimer** [comment] 2020-08-28 18:50
I basically have everything ready for 5.15 but I still work on esync/fsync support.

**Comment by M-Reimer** [comment] 2020-08-29 18:21
My work is here: https://github.com/M-Reimer/wine-lol/tree/new_wine_work

Does open the client. Does not allow to start a game. **So only try with practice tool!**

Maybe the reason for this is my try to get esync/fsync to work. A new patch which can be fiddled into the "master" branch can be found here:
https://github.com/M-Reimer/wine-lol/blob/new_wine_work/wine-lol/wine-lol-bug-47198-fix.patch.new

I'm giving up at this point. Maybe someone else wants to do a few tries. At this point I would even say let's give up completely on esync and fsync. The patch mess really sucks. So maybe you want to give this a try with the patch I've linked above and wine 5.15? But, of course, with the master branch in this case and not with my esync/fsync patched development branch.

**Comment by lolzballs** [comment] 2020-08-29 19:47
Sorry, not really understanding. Is the patch you sent (bug 47198) *the* wine-lol patch (i.e. the one that gets wine to work for lol)? I don't think esync/fsync matters for this issue so if it is I will try that patch with wine-staging 5.15.

**Comment by M-Reimer** [comment] 2020-08-29 21:35
Yes. This is the patch that is needed to make wine run LoL (together with wine-lol-glibc). Maybe that's all we need to make wine 5.15 work with LoL. And just lets forget about esync/fsync. Both will be reworked really soon anyway.

**Comment by M-Reimer** [comment] 2020-08-30 18:00
Did a few more tries today. The patch I prepared does not work. There seems to be some new check which errors while configure.

So I reworked the patch and got a build running.

And now it seems like we are stuck here:
https://bugs.winehq.org/show_bug.cgi?id=49412

So at least for now we are stuck at Wine 5.6.

**Comment by M-Reimer** [comment] 2020-08-31 11:22
Here my work for a wine update without esync/fsync:

https://github.com/M-Reimer/wine-lol/tree/wine-5.16

Just to archive it for later use. Again: Does not work and it seems like we should prepare for being stuck with wine 5.6 for quite some time now.

**Comment by lolzballs** [comment] 2020-08-31 15:47
Unfortunately 5.16 didn't fix the windowing issue either. I'll stick with 5.6 and I'll do a little digging on my own to see if I can figure out the issue.

**Comment by M-Reimer** [comment] 2020-09-14 11:32
If even 5.16 does not fix the problem and especially if this problem seems to be pretty rare (can't reproduce) I think we can close this one.
If you find the reason for this (maybe it's a specific DXVK version which causes this. Who knows, ...) then please create a new Issue for this.

**Closed by M-Reimer** 2020-09-14 11:32 UTC
Labels: later
