### ISSUE TITLE
Black screen client lol

### ISSUE THREAD

**Issue by DRL-28** [M-Reimer/wine-lol#21] opened 2019-07-04 13:10 UTC
After starting the client, I only see a black screen. If I run the client through the fault of the system, then everything is fine. 

video
https://yadi.sk/i/ym2Z87xqqfhJRQ

**Comment by M-Reimer** [comment] 2019-07-05 08:04
I've seen this before. I'm trying to do a build on a dedicated build virtual machine and I was sure this is caused by my building on a VM. Interesting to see that it happens on real hardware, too.

Can you please download the wine-lol PKGBUILD and push the wine version to the latest stable version?
I'm on a trip for some days and knowing that it can be fixed by just updating wine would make it much easier for me to fix this when I'm back home.

**Comment by M-Reimer** [comment] 2019-07-05 08:06
Of course you would have to use makepkg for building then. Please tell me if the new wine version makes any difference. Thanks in advance.

**Comment by kleest** [comment] 2019-07-05 20:34
That's a problem with GCC 9. It is solved with Wine 4.11; alternatively, apply [this patch](https://source.winehq.org/patches/data/166316) with Wine 4.9.

**Comment by M-Reimer** [comment] 2019-07-05 20:41
Thank you. Will try this next week.

**Comment by DRL-28** [comment] 2019-07-06 00:23
I downloaded the last wine-lol PKGBUILD and edited it indicating the version of wine 4.11 there. After a long compilation, the client lol started up normally.

**Comment by bloodlvst** [comment] 2019-07-06 02:31
I'm also having this issue. So does the above just mean that I need to change makefiles to patch 4.11 instead of patching 4.9, and everything else is the same?

**Comment by M-Reimer** [comment] 2019-07-06 06:22
Seems like that. I'll update this on AUR as soon as possible.

**Comment by bloodlvst** [comment] 2019-07-06 07:44
I just confirmed and tested, all working now. Made a commit if you wish to use it. :)

**Comment by M-Reimer** [comment] 2019-07-06 07:57
Will only work if you change the .SRCINFO file in the same commit. If you don't, then the commit will not be accepted by the AUR git server.

If you create a pull request this way, then I can accept it, but I'm still not able to push to AUR until Monday

**Comment by M-Reimer** [comment] 2019-07-07 06:58
About the .SRCINFO
https://wiki.archlinux.org/index.php/.SRCINFO

**Comment by M-Reimer** [comment] 2019-07-08 19:19
I'm running a test-build currently. Let's see if it works with 4.12.1

**Comment by M-Reimer** [comment] 2019-07-08 20:02
Seems to be fixed with 4.12.1
I've pushed this update to AUR.

**Closed by M-Reimer** 2019-07-08 20:02 UTC
